# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: !!null
google_analytics: !!null
title: Ryan Everett
host: 0.0.0.0

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Ryan Everett

description: Stylish Jekyll Theme
author:
  name: Ryan Everett
  email: beebooboo@bop
  github: Changer098
  twitter: Changer098
  bio: I make stuffz
  email_md5: 726351295ec82e145928582f595aa3aa
  theme_link: https://github.com/Changer098/dbyll
  picture_link: https://www.reddit.com/r/wholesomememes/comments/8ssbh1/i_recently_got_a_tablet/

collections:
  about_me:
    output: true
  projects:
    output: true
  test-collect:
    order:
      introduction.md
      basic-setup.md
  

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
projects_path: projects.html
about_path: about.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
